[project]
name = "nix-pytorch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.5.2",
    "diffusers>=0.32.2",
    "numpy>=2.2.3",
    "torch>=2.6.0",
    "transformers>=4.49.0",
]
